name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm install
        npm run build
        
    - name: Deploy Gh Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        jekyll: false
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
